language: python # => 1
python: # => 2
  - "3.6.8"
services: # => 3
  - postgresql
install: # => 5
  - pip install -r requirements.txt
before_script: # => 6
  - psql -c 'create database travis_ci_test;' -U postgres
  - cd GetInBackendRebuild
  - cp .env.example .env
  - cd ..
script: # => 7
  - yes yes | coverage run --source='.' manage.py test
  - coverage report --omit 'venv/*','app/migrations/*','app/tests/*','GetInBackendRebuild/wsgi.py','app/__init__.py','app/utils/__init__.py'