language: python # => 1
    python: # => 2
      - "3.6.8"
    services: # => 3
      - postgresql
    env: # => 4
      -DJANGO=2.2.8 DB=postgresql
    install: # => 5
      - pip install -r requirements.txt
    before_script: # => 6
      - psql -c 'create database travis_ci_test;' -U postgres
    script: # => 7
      - python manage.py test
