# user's gender
GENDER_MALE = 0
GENDER_FEMALE = 1
GENDER_NOT_SPECIFIED = 2

PRIMARY_LEVEL = "primary_level"
O_LEVEL = "o_level"
A_LEVEL = "a_level"
TERTIARY_LEVEL = "tertiary"


SINGLE = "single"
MARRIED = "married"
DIVORCED = "divorced"


HOME = "home"
HEALTH_FACILITY = "health_facility"

USER_TYPE_DEVELOPER = 1
USER_TYPE_DHO = 2
USER_TYPE_CHEW = 3
USER_TYPE_MIDWIFE = 4
USER_TYPE_AMBULANCE = 5
USER_TYPE_MANAGER = 6