# Generated by Django 2.2.6 on 2019-10-08 11:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_girl_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='girl',
            name='trimester',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(1)]),
        ),
    ]
