# Generated by Django 2.2.6 on 2019-11-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191116_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='girl',
            name='marital_status',
            field=models.CharField(choices=[('Married', 'Married'), ('Divorced', 'Divorced'), ('Single', 'Single')], default='Single', max_length=250),
        ),
        migrations.AlterField(
            model_name='user',
            name='firebase_device_id',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
