# Generated by Django 2.2.6 on 2019-10-08 10:06

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191008_0903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='girl',
            old_name='phone',
            new_name='next_of_kin_phone_number',
        ),
        migrations.AddField(
            model_name='girl',
            name='dob',
            field=models.DateTimeField(default='0752454555'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='girl',
            name='education_level',
            field=models.CharField(choices=[('primary_level', 'Primary Level'), ('o_level', 'O Level'), ('a_level', 'A Level'), ('tertiary', 'Tertiary Level')], default='primary_level', max_length=250),
        ),
        migrations.AddField(
            model_name='girl',
            name='last_menstruation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='girl',
            name='marital_status',
            field=models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced')], default='single', max_length=250),
        ),
        migrations.AddField(
            model_name='girl',
            name='next_of_kin_name',
            field=models.CharField(default='maria', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='girl',
            name='phone_number',
            field=models.CharField(default='0752454555', max_length=12, validators=[django.core.validators.RegexValidator(message='Wrong phone number format', regex='^(07)[0-9]{8}$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='girl',
            name='trimester',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
