# Generated by Django 2.2.6 on 2019-10-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191008_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='girl',
            name='createdAt',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='girl',
            name='dob',
            field=models.DateField(),
        ),
    ]
