# Generated by Django 2.2.6 on 2019-10-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20191008_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='girl',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='girl',
            name='last_menstruation_date',
            field=models.DateField(),
        ),
    ]
