# Generated by Django 2.2.6 on 2019-11-18 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20191117_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='missed_anc_before',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='followup',
            name='missed_anc_reason',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='girl',
            name='marital_status',
            field=models.CharField(choices=[('Divorced', 'Divorced'), ('Single', 'Single'), ('Married', 'Married')], default='Single', max_length=250),
        ),
    ]
