# Generated by Django 2.2.6 on 2019-10-23 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20191023_1357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='delivery_locations',
            new_name='delivery_location',
        ),
    ]
