# Generated by Django 2.2.6 on 2019-10-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20191010_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='chew',
            name='user_type',
            field=models.CharField(default='chew', max_length=50),
        ),
        migrations.AddField(
            model_name='dho',
            name='user_type',
            field=models.CharField(default='dho', max_length=50),
        ),
        migrations.AddField(
            model_name='midwife',
            name='user_type',
            field=models.CharField(default='midwife', max_length=50),
        ),
    ]
