# Generated by Django 2.2.6 on 2019-10-25 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20191025_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='girl',
            name='marital_status',
            field=models.CharField(choices=[('married', 'Married'), ('divorced', 'Divorced'), ('single', 'Single')], default='single', max_length=250),
        ),
        migrations.CreateModel(
            name='MappingEncounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_appointment', models.DateTimeField(auto_now_add=True)),
                ('using_family_planning', models.BooleanField(default=True)),
                ('no_family_planning_reason', models.CharField(max_length=250)),
                ('family_planning_type', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('girl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Girl')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
