# Generated by Django 2.2.6 on 2019-10-10 15:01

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20191010_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('user_type', models.CharField(default='ambulance', max_length=50)),
                ('number_place', models.CharField(max_length=50)),
                ('midwife_relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Midwife')),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Parish')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('app.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
