# Generated by Django 2.2.6 on 2019-10-17 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_ambulance'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followup_reason', models.TextField()),
                ('actionTaken', models.CharField(max_length=50)),
                ('blurred_vision', models.BooleanField(default=False)),
                ('bleeding_heavily', models.BooleanField(default=False)),
                ('fever', models.BooleanField(default=False)),
                ('swollen_feet', models.BooleanField(default=False)),
                ('next_appointment', models.DateTimeField(auto_now_add=True)),
                ('follow_date', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.CHEW')),
                ('girl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Girl')),
                ('midwife', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Midwife')),
            ],
        ),
    ]
