# Generated by Django 2.2.6 on 2019-10-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20191025_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='girl',
            name='marital_status',
            field=models.CharField(choices=[('married', 'Married'), ('single', 'Single'), ('divorced', 'Divorced')], default='single', max_length=250),
        ),
    ]
