# Generated by Django 2.2.6 on 2019-12-04 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20191204_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='girl',
            name='marital_status',
            field=models.CharField(choices=[('Married', 'Married'), ('Divorced', 'Divorced'), ('Single', 'Single')], default='Single', max_length=250),
        ),
    ]
