# Generated by Django 2.2.6 on 2019-10-21 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_followup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='actionTaken',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followup_reason', models.TextField()),
                ('actionTaken', models.CharField(max_length=200)),
                ('received_postnatal_care', models.BooleanField(default=True)),
                ('is_mother_alive', models.BooleanField(default=True)),
                ('is_baby_alive', models.BooleanField(default=True)),
                ('baby_death_date', models.DateTimeField()),
                ('baby_birth_date', models.DateTimeField()),
                ('mother_death_date', models.DateTimeField()),
                ('using_family_planning', models.BooleanField(default=True)),
                ('no_family_planning_reason', models.CharField(max_length=250)),
                ('family_planning_type', models.CharField(max_length=250)),
                ('health_facility', models.CharField(max_length=200)),
                ('delivery_date', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.CHEW')),
                ('girl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Girl')),
                ('midwife', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Midwife')),
            ],
        ),
    ]
