# Generated by Django 2.2.6 on 2019-10-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20191025_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='girl',
            name='marital_status',
            field=models.CharField(choices=[('divorced', 'Divorced'), ('married', 'Married'), ('single', 'Single')], default='single', max_length=250),
        ),
        migrations.AlterField(
            model_name='mappingencounter',
            name='next_appointment',
            field=models.DateTimeField(),
        ),
    ]
