# Generated by Django 2.2.6 on 2019-10-25 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20191025_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='girl',
            name='marital_status',
            field=models.CharField(choices=[('married', 'Married'), ('divorced', 'Divorced'), ('single', 'Single')], default='single', max_length=250),
        ),
        migrations.AlterField(
            model_name='mappingencounter',
            name='no_family_planning_reason',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
