# Generated by Django 2.2.8 on 2020-08-10 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200805_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='girl',
            name='voucher_card',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='girl',
            name='marital_status',
            field=models.CharField(choices=[('Married', 'Married'), ('Single', 'Single'), ('Divorced', 'Divorced')], default='Single', max_length=250),
        ),
        migrations.CreateModel(
            name='MSIService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(choices=[('ANC1', 'ANC1'), ('ANC2', 'ANC2'), ('ANC3', 'ANC3'), ('ANC4', 'ANC4'), ('Delivery', 'Delivery'), ('Family Planning', 'Family Planning')], default='ANC1', max_length=250)),
                ('girl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Girl')),
            ],
        ),
    ]
