# Generated by Django 2.2.6 on 2019-10-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20191025_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='family_planning_type',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='no_family_planning_reason',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='mappingencounter',
            name='family_planning_type',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
