# Generated by Django 2.2.6 on 2019-10-25 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20191025_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappingencounter',
            name='bleeding_heavily',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mappingencounter',
            name='blurred_vision',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mappingencounter',
            name='fever',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mappingencounter',
            name='swollen_feet',
            field=models.BooleanField(default=False),
        ),
    ]
