# Generated by Django 2.2.8 on 2020-08-11 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200811_1907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='girl',
            old_name='voucher_card',
            new_name='voucher_number',
        ),
        migrations.AlterField(
            model_name='girl',
            name='marital_status',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced')], default='Single', max_length=250),
        ),
    ]
