# Generated by Django 2.2.8 on 2020-09-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20200818_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='girl',
            name='disabled',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='girl',
            name='nationality',
            field=models.CharField(blank=True, default='Ugandan', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='girl',
            name='marital_status',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced')], default='Single', max_length=250),
        ),
    ]
