# Generated by Django 2.2.6 on 2019-10-30 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20191025_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='next_appointment',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='girl',
            name='marital_status',
            field=models.CharField(choices=[('married', 'Married'), ('divorced', 'Divorced'), ('single', 'Single')], default='single', max_length=250),
        ),
    ]
