# Generated by Django 2.2.8 on 2020-11-26 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20201110_1544'),
        ('app', '0018_auto_20201105_1123'),
    ]

    operations = [
    ]
