# Generated by Django 2.2.6 on 2019-10-30 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20191030_0853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='health_facility',
        ),
        migrations.AddField(
            model_name='delivery',
            name='marital_status',
            field=models.CharField(choices=[('married', 'Married'), ('single', 'Single'), ('divorced', 'Divorced')], default='single', max_length=250),
        ),
        migrations.AlterField(
            model_name='girl',
            name='marital_status',
            field=models.CharField(choices=[('married', 'Married'), ('single', 'Single'), ('divorced', 'Divorced')], default='single', max_length=250),
        ),
    ]
