# Generated by Django 2.2.6 on 2019-10-30 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20191030_0923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='marital_status',
        ),
        migrations.AddField(
            model_name='delivery',
            name='health_facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.HealthFacility'),
        ),
        migrations.AlterField(
            model_name='girl',
            name='marital_status',
            field=models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced')], default='single', max_length=250),
        ),
    ]
