# Generated by Django 2.2.8 on 2020-12-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20201217_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentsmslog',
            name='message_type',
            field=models.CharField(choices=[('HEALTH_MESSAGES', 'HEALTH_MESSAGES'), ('APPOINTMENT_REMINDER_MESSAGES', 'APPOINTMENT_REMINDER_MESSAGES')], default='HEALTH_MESSAGES', max_length=200),
        ),
        migrations.AlterField(
            model_name='girl',
            name='marital_status',
            field=models.CharField(choices=[('Single', 'Single'), ('Divorced', 'Divorced'), ('Married', 'Married')], default='Single', max_length=250),
        ),
    ]
