# Generated by Django 2.2.6 on 2019-10-30 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20191030_0927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followup',
            name='follow_date',
        ),
        migrations.AlterField(
            model_name='followup',
            name='action_taken',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='followup',
            name='followup_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='girl',
            name='marital_status',
            field=models.CharField(choices=[('married', 'Married'), ('single', 'Single'), ('divorced', 'Divorced')], default='single', max_length=250),
        ),
    ]
