# Generated by Django 2.2.8 on 2021-04-22 08:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20201217_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='msiservice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='girl',
            name='marital_status',
            field=models.CharField(choices=[('Divorced', 'Divorced'), ('Single', 'Single'), ('Married', 'Married')], default='Single', max_length=250),
        ),
        migrations.AlterField(
            model_name='sentsmslog',
            name='message_type',
            field=models.CharField(choices=[('HEALTH_MESSAGES', 'HEALTH_MESSAGES'), ('APPOINTMENT_REMINDER_MESSAGES', 'APPOINTMENT_REMINDER_MESSAGES'), ('APP_USAGE_REMINDER_MESSAGES', 'APP_USAGE_REMINDER_MESSAGES')], default='HEALTH_MESSAGES', max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='msiservice',
            unique_together={('girl', 'option')},
        ),
    ]
