# Generated by Django 2.2.6 on 2019-10-30 12:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20191030_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='completed_visits',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='appointment',
            name='pending_visits',
            field=models.IntegerField(default=3, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Missed', 'Missed'), ('Attended', 'Missed'), ('Expected', 'Expected'), ('Missed', 'Missed')], default='Expected', max_length=250),
        ),
        migrations.AlterField(
            model_name='girl',
            name='education_level',
            field=models.CharField(choices=[('Primary level', 'Primary Level'), ('O level', 'O Level'), ('A level', 'A Level'), ('Tertiary', 'Tertiary Level')], default='Primary level', max_length=250),
        ),
        migrations.AlterField(
            model_name='girl',
            name='marital_status',
            field=models.CharField(choices=[('Divorced', 'Divorced'), ('Married', 'Married'), ('Single', 'Single')], default='Single', max_length=250),
        ),
    ]
