# Generated by Django 2.2.6 on 2019-10-30 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20191030_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Missed', 'Missed'), ('Attended', 'Missed'), ('Expected', 'Expected'), ('Completed', 'Completed')], default='Expected', max_length=250),
        ),
        migrations.AlterField(
            model_name='girl',
            name='marital_status',
            field=models.CharField(choices=[('Single', 'Single'), ('Divorced', 'Divorced'), ('Married', 'Married')], default='Single', max_length=250),
        ),
    ]
