# Generated by Django 2.2.8 on 2021-10-27 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20211026_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='girl',
            name='disablility',
            field=models.CharField(blank=True, default='None', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='girl',
            name='marital_status',
            field=models.CharField(choices=[('Divorced', 'Divorced'), ('Married', 'Married'), ('Single', 'Single')], default='Single', max_length=250),
        ),
    ]
