# Generated by Django 2.2.8 on 2021-10-27 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20211027_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='girl',
            name='education_level',
            field=models.CharField(choices=[('Primary level', 'Primary Level'), ('O level', 'O Level'), ('A level', 'A Level'), ('Tertiary', 'Tertiary Level'), ('None', 'None')], default='Primary level', max_length=250),
        ),
        migrations.AlterField(
            model_name='girl',
            name='marital_status',
            field=models.CharField(choices=[('Single', 'Single'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed'), ('Married', 'Married')], default='Single', max_length=250),
        ),
        migrations.AlterField(
            model_name='healthfacility',
            name='facility_level',
            field=models.CharField(blank=True, help_text='0 - Hospital, 1 - HFI, 2 - HFII, 3 - HFIII, 4 - HFIV', max_length=9, null=True),
        ),
    ]
