# Generated by Django 2.2.8 on 2021-10-27 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20211027_1050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='girl',
            old_name='disablility',
            new_name='disability',
        ),
        migrations.AlterField(
            model_name='girl',
            name='marital_status',
            field=models.CharField(choices=[('Divorced', 'Divorced'), ('Married', 'Married'), ('Widowed', 'Widowed'), ('Single', 'Single')], default='Single', max_length=250),
        ),
    ]
