# Generated by Django 2.2.8 on 2021-10-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20211028_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disability',
            name='name',
            field=models.CharField(default='unknown', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='girl',
            name='marital_status',
            field=models.CharField(choices=[('Divorced', 'Divorced'), ('Single', 'Single'), ('Widowed', 'Widowed'), ('Married', 'Married')], default='Single', max_length=250),
        ),
    ]
