# Generated by Django 2.2.6 on 2019-11-01 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_girl_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='girl',
            name='user',
        ),
        migrations.AlterField(
            model_name='girl',
            name='marital_status',
            field=models.CharField(choices=[('Divorced', 'Divorced'), ('Single', 'Single'), ('Married', 'Married')], default='Single', max_length=250),
        ),
    ]
