# Generated by Django 2.2.8 on 2021-11-05 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20211028_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='girl',
            name='marital_status',
            field=models.CharField(choices=[('Widowed', 'Widowed'), ('Divorced', 'Divorced'), ('Single', 'Single'), ('Married', 'Married')], default='Single', max_length=250),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('developer', 'developer'), ('dho', 'dho'), ('chew', 'chew'), ('manager', 'manager'), ('midwife', 'midwife'), ('ambulance', 'ambulance')], default='developer', help_text='developer - Developer, dho - DHO, chew - CHEW, midwife - Midwife, ambulance - Ambulance, manager - Manager', max_length=50),
        ),
    ]
