# Generated by Django 2.2.6 on 2019-11-01 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_auto_20191101_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mappingencounter',
            name='next_appointment',
        ),
        migrations.AlterField(
            model_name='girl',
            name='marital_status',
            field=models.CharField(choices=[('Divorced', 'Divorced'), ('Married', 'Married'), ('Single', 'Single')], default='Single', max_length=250),
        ),
    ]
