# Generated by Django 2.2.6 on 2019-11-02 15:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20191101_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappingencounter',
            name='attended_anc_visit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mappingencounter',
            name='voucher_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='pending_visits',
            field=models.IntegerField(default=2, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(0)]),
        ),
    ]
