# Generated by Django 2.2.8 on 2021-12-03 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_auto_20211201_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='girl',
            name='marital_status',
            field=models.CharField(choices=[('Single', 'Single'), ('Widowed', 'Widowed'), ('Divorced', 'Divorced'), ('Married', 'Married')], default='Single', max_length=250),
        ),
        migrations.AlterField(
            model_name='user',
            name='midwife',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
