# Generated by Django 2.2.6 on 2019-11-02 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_auto_20191102_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='number_plate',
        ),
        migrations.AlterField(
            model_name='girl',
            name='marital_status',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced')], default='Single', max_length=250),
        ),
        migrations.AlterField(
            model_name='user',
            name='number_place',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
