# Generated by Django 2.2.6 on 2019-11-02 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_auto_20191102_2031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='number_place',
            new_name='number_plate',
        ),
        migrations.AlterField(
            model_name='girl',
            name='marital_status',
            field=models.CharField(choices=[('Married', 'Married'), ('Single', 'Single'), ('Divorced', 'Divorced')], default='Single', max_length=250),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.IntegerField(choices=[('Developer', 'Developer'), ('Dho', 'DHO'), ('Chew', 'CHEW'), ('Midwife', 'Midwife'), ('Ambulance', 'Ambulance')], default='Developer'),
        ),
    ]
