# Generated by Django 2.2.6 on 2019-11-02 21:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_auto_20191102_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='girl',
            name='marital_status',
            field=models.CharField(choices=[('Married', 'Married'), ('Single', 'Single'), ('Divorced', 'Divorced')], default='Single', max_length=250),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Wrong phone number format', regex='^(07)[0-9]{8}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(1, 'Developer'), (2, 'DHO'), (3, 'CHEW'), (4, 'Midwife'), (5, 'Ambulance')], default=1, help_text='1 - Developer, 2 - DHO, 3 - CHEW, 4 - Midwife, 5 - Ambulance, 6 - Manager'),
        ),
    ]
