# Generated by Django 2.2.6 on 2019-11-04 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_auto_20191104_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='follow_up_action_taken',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='girl',
            name='marital_status',
            field=models.CharField(choices=[('Divorced', 'Divorced'), ('Single', 'Single'), ('Married', 'Married')], default='Single', max_length=250),
        ),
    ]
