# Generated by Django 2.2.6 on 2019-11-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_auto_20191104_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='girl',
            name='marital_status',
            field=models.CharField(choices=[('Divorced', 'Divorced'), ('Single', 'Single'), ('Married', 'Married')], default='Single', max_length=250),
        ),
    ]
