# Generated by Django 2.2.6 on 2019-11-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_auto_20191104_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followup',
            name='action_taken',
        ),
        migrations.RemoveField(
            model_name='followup',
            name='action_taken_by_vht',
        ),
        migrations.RemoveField(
            model_name='followup',
            name='anc_card',
        ),
        migrations.RemoveField(
            model_name='followup',
            name='follow_up_reason',
        ),
        migrations.RemoveField(
            model_name='followup',
            name='missed_anc_reason',
        ),
        migrations.RemoveField(
            model_name='followup',
            name='next_appointment',
        ),
        migrations.AlterField(
            model_name='girl',
            name='marital_status',
            field=models.CharField(choices=[('Married', 'Married'), ('Divorced', 'Divorced'), ('Single', 'Single')], default='Single', max_length=250),
        ),
    ]
