# Generated by Django 2.2.6 on 2019-11-04 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_auto_20191104_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='delivery_location',
            field=models.CharField(choices=[('Home', 'Home'), ('Health facility', 'Health Facility')], default='Home', max_length=250),
        ),
        migrations.AlterField(
            model_name='girl',
            name='marital_status',
            field=models.CharField(choices=[('Married', 'Married'), ('Divorced', 'Divorced'), ('Single', 'Single')], default='Single', max_length=250),
        ),
    ]
