# Generated by Django 2.2.6 on 2019-11-05 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_auto_20191105_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentencounter',
            name='bleeding_heavily',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointmentencounter',
            name='blurred_vision',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointmentencounter',
            name='fever',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointmentencounter',
            name='swollen_feet',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='girl',
            name='marital_status',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced')], default='Single', max_length=250),
        ),
    ]
