# Generated by Django 2.2.6 on 2019-11-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_auto_20191105_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='girl',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='girl',
            name='marital_status',
            field=models.CharField(choices=[('Divorced', 'Divorced'), ('Single', 'Single'), ('Married', 'Married')], default='Single', max_length=250),
        ),
    ]
