# Generated by Django 2.2.6 on 2019-11-06 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0063_auto_20191105_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='completed_visits',
        ),
    ]
