# Generated by Django 2.2.6 on 2019-11-06 07:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0064_remove_appointment_completed_visits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='pending_visits',
        ),
        migrations.AddField(
            model_name='girl',
            name='pending_visits',
            field=models.IntegerField(default=2, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='girl',
            name='marital_status',
            field=models.CharField(choices=[('Divorced', 'Divorced'), ('Single', 'Single'), ('Married', 'Married')], default='Single', max_length=250),
        ),
    ]
