# Generated by Django 2.2.6 on 2019-11-06 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0067_auto_20191106_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Missed', 'Missed'), ('Attended', 'Attended'), ('Expected', 'Expected')], default='Expected', max_length=250),
        ),
    ]
