# Generated by Django 2.2.6 on 2019-11-11 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0072_auto_20191108_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='girl',
            name='marital_status',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced')], default='Single', max_length=250),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default='female', help_text='male - Male, female - Female', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('developer', 'Developer'), ('dho', 'DHO'), ('chew', 'CHEW'), ('midwife', 'Midwife'), ('ambulance', 'Ambulance')], default='developer', help_text='developer - Developer, dho - DHO, chew - CHEW, midwife - Midwife, ambulance - Ambulance, manager - Manager', max_length=50),
        ),
    ]
