# Generated by Django 2.2.6 on 2019-11-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0073_auto_20191111_0959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='delivery_date',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='girl',
            name='marital_status',
            field=models.CharField(choices=[('Divorced', 'Divorced'), ('Single', 'Single'), ('Married', 'Married')], default='Single', max_length=250),
        ),
    ]
