# Generated by Django 2.2.6 on 2019-11-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0076_auto_20191111_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smsmodel',
            name='successful',
        ),
        migrations.AddField(
            model_name='smsmodel',
            name='status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='girl',
            name='marital_status',
            field=models.CharField(choices=[('Divorced', 'Divorced'), ('Single', 'Single'), ('Married', 'Married')], default='Single', max_length=250),
        ),
    ]
