# Generated by Django 2.2.6 on 2019-11-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0079_auto_20191111_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('developer', 'developer'), ('dho', 'dho'), ('chew', 'chew'), ('midwife', 'midwife'), ('ambulance', 'ambulance')], default='developer', help_text='developer - Developer, dho - DHO, chew - CHEW, midwife - Midwife, ambulance - Ambulance, manager - Manager', max_length=50),
        ),
    ]
