# Generated by Django 2.2.6 on 2019-11-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0080_auto_20191112_1303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='appointmentencounter',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='delivery',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='followup',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='girl',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='mappingencounter',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='smsmodel',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='girl',
            name='marital_status',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced')], default='Single', max_length=250),
        ),
    ]
