# Generated by Django 2.2.6 on 2019-11-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0084_auto_20191114_0923'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyPlanning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pre', 'Pre'), ('Post', 'Post')], default='Pre', max_length=250)),
                ('method', models.TextField(blank=True, null=True)),
                ('no_family_planning_reason', models.CharField(blank=True, max_length=250, null=True)),
                ('using_family_planning', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blurred_vision', models.BooleanField(default=False)),
                ('bleeding_heavily', models.BooleanField(default=False)),
                ('fever', models.BooleanField(default=False)),
                ('swollen_feet', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='mappingencounter',
            name='bleeding_heavily',
        ),
        migrations.RemoveField(
            model_name='mappingencounter',
            name='blurred_vision',
        ),
        migrations.RemoveField(
            model_name='mappingencounter',
            name='family_planning_type',
        ),
        migrations.RemoveField(
            model_name='mappingencounter',
            name='fever',
        ),
        migrations.RemoveField(
            model_name='mappingencounter',
            name='no_family_planning_reason',
        ),
        migrations.RemoveField(
            model_name='mappingencounter',
            name='swollen_feet',
        ),
        migrations.RemoveField(
            model_name='mappingencounter',
            name='using_family_planning',
        ),
        migrations.RemoveField(
            model_name='mappingencounter',
            name='voucher_number',
        ),
        migrations.AlterField(
            model_name='girl',
            name='marital_status',
            field=models.CharField(choices=[('Single', 'Single'), ('Divorced', 'Divorced'), ('Married', 'Married')], default='Single', max_length=250),
        ),
    ]
