# Generated by Django 2.2.6 on 2019-11-14 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0086_auto_20191114_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappingencounter',
            name='family_planning',
            field=models.ManyToManyField(to='app.FamilyPlanning'),
        ),
        migrations.AddField(
            model_name='mappingencounter',
            name='observation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Observation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='girl',
            name='marital_status',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced')], default='Single', max_length=250),
        ),
    ]
