# Generated by Django 2.2.6 on 2019-11-14 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0090_auto_20191114_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentencounter',
            name='girl',
        ),
        migrations.RemoveField(
            model_name='appointmentencounter',
            name='user',
        ),
        migrations.AlterField(
            model_name='girl',
            name='marital_status',
            field=models.CharField(choices=[('Married', 'Married'), ('Divorced', 'Divorced'), ('Single', 'Single')], default='Single', max_length=250),
        ),
    ]
