# Generated by Django 2.2.6 on 2019-11-14 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0091_auto_20191114_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='girl',
            name='next_of_kin_first_name',
        ),
        migrations.RemoveField(
            model_name='girl',
            name='next_of_kin_last_name',
        ),
        migrations.AlterField(
            model_name='girl',
            name='marital_status',
            field=models.CharField(choices=[('Divorced', 'Divorced'), ('Single', 'Single'), ('Married', 'Married')], default='Single', max_length=250),
        ),
    ]
